# Generated by Django 6.0.3 on 2026-03-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
