# Generated by Django 6.0.3 on 2026-03-15 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_addresses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addresses",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
