# Generated by Django 6.0.3 on 2026-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_addresses_options_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English(US)"), ("fa", "Persian")],
                default="en-us",
                max_length=5,
                verbose_name="Language",
            ),
        ),
    ]
