# Generated by Django 6.0.3 on 2026-03-18 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="language",
        ),
    ]
