# Generated by Django 6.0.3 on 2026-04-08 12:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_customuser_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="IR", unique=True
            ),
        ),
        migrations.DeleteModel(
            name="PhoneNumber",
        ),
    ]
