# Generated by Django 6.0.3 on 2026-04-08 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_customuser_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
