# Generated by Django 6.0.3 on 2026-04-10 15:14

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_addresses_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresses",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[accounts.validators.postal_code_validator],
                verbose_name="Postal Code",
            ),
        ),
    ]
