# Generated by Django 6.0.3 on 2026-04-11 17:39

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_addresses_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresses",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[accounts.validators.postal_code_validator],
                verbose_name="Postal Code",
            ),
        ),
    ]
