"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path
from uuid import uuid4

from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG_MODE")

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # allauth
    "allauth",
    "allauth.account",
    # allauth extra social accounts
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.openid_connect",
    #     third party apps
    "crispy_forms",
    "crispy_bootstrap5",
    "django_jalali",
    "django_madval",
    "rosetta",
    # "debug_toolbar",
    "phonenumber_field",
    "iranian_cities",
    "dal",
    "dal_select2",
    "axes",
    "widget_tweaks",
    "django_elasticsearch_dsl",
    #     local apps
    "accounts",
    "shop",
    "cart",
    "orders",
    "payment",
    "support",
]

PHONENUMBER_DEFAULT_REGION = "IR"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",  # debug toolbar
    "allauth.account.middleware.AccountMiddleware",  # allauth
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID"),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

ACCOUNT_SESSION_REMEMBER = True

ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True

AUTH_USER_MODEL = "accounts.CustomUser"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.joinpath("templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # `allauth` needs this from django
                "django.template.context_processors.request",
                #     custom context processor
                "cart.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTHENTICATION_BACKENDS = [
    # axes backend
    "axes.backends.AxesStandaloneBackend",
    # custom authentication backends
    "accounts.auth_backends.EmailOrPhoneBackend",
    "accounts.auth_backends.OTPBackend",
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth مرتبط با
SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# --- تنظیمات بهینه SQLite برای Django 5.1 به بالا ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,  # افزایش timeout به 20 ثانیه
            "transaction_mode": "IMMEDIATE",  # بسیار مهم برای جلوگیری از قفل شدگی
            "init_command": """
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=NORMAL;
                PRAGMA cache_size=10000;
                PRAGMA mmap_size=134217728;
            """,
        },
    }
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": os.getenv("DJANGO_DATABASE_NAME"),
    #     "USER": os.getenv("DJANGO_DATABASE_USERNAME"),
    #     "PASSWORD": os.getenv("DJANGO_DATABASE_PASSWORD"),
    #     "HOST": "localhost",
    #     "PORT": 5432,
    #     # 'ENGINE': 'django.db.backends.sqlite3',
    #     # 'NAME': BASE_DIR / 'db.sqlite3',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "/static/"

# ================ Crispy Forms ================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ================ End Crispy Forms ================

# =============== Media Files ====================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =============== End Media Files ====================

# ================ Email ====================
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_HOST = env("SMTP_SERVER")
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True
# EMAIL_PORT = env("SMTP_PORT")
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER =env("EMAIL_ADDRESS")
# EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")

# ================ End Email ================

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# ================ Caching System ================

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_LOCATION"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
        },
    },
    "axes_cache": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },
}

OTP_REDIS_PREFIX = "otp:"
OTP_EXPIRE_SECONDS = 120  # دو دقیقه
OTP_RATE_LIMIT_SECONDS = 60  # محدودیت ارسال مجدد

# ================ End Caching System ================

# ================ Django-axes config ================

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_LOCK_OUT_AT_FAILURE = True
AXES_LOCKOUT_CALLABLE = "accounts.utils.lockout_response"
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]

# زمان خنک‌سازی بر حسب ثانیه (مثلاً 1 ساعت)
AXES_COOLOFF_TIME = 3600

# تنظیم حیاتی برای جلوگیری از بلاک اشتباه viewهای OTP
AXES_ENABLED = True
AXES_ACCESS_FAILURE_LOG_PER_USER_LIMIT = 50
AXES_HANDLER = "axes.handlers.cache.AxesCacheHandler"
AXES_CACHE = "axes_cache"

# ================ End django-axes config ================

# =================== Zarinpal Gateway Settings =======================

ZARINPAL_MERCHANT_ID = os.getenv("ZARINPAL_MERCHANT_ID")

# ==========================================
# settings.py

# تنظیمات Elasticsearch بدون Docker
ELASTICSEARCH_DSL = {
    "default": {
        "hosts": os.getenv("ELASTICSEARCH_DSL_HOST"),  # اضافه کردن http://
        "timeout": 30,
    },
}

# اگر Elasticsearch روی پورت دیگری است:
# ELASTICSEARCH_DSL = {
#     'default': {
#         'hosts': 'localhost:9201',
#         'timeout': 30,
#     },
# }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} - {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
        "sql_formatter": {
            "format": "\n🔵 SQL ({duration:.2f}s) - {sql}\n📍 {stack}\n",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "sql_threshold": {
            "()": "django.utils.log.CallbackFilter",
            "callback": lambda record: hasattr(record, "duration")
            and record.duration > 0.1,  # فقط کوئری‌های بالای 100 میلی‌ثانیه
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
        "sql_console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "sql_formatter",
            "filters": ["require_debug_true", "sql_threshold"],
        },
    },
    "loggers": {
        # لاگ کوئری‌های کند دیتابیس (بالای 100 میلی‌ثانیه)
        "django.db.backends": {
            "level": "DEBUG",
            "handlers": ["sql_console"],
            "propagate": False,
        },
        # لاگ درخواست‌های HTTP (زمان پاسخ)
        "django.request": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
        # لاگ عملیات کش (Redis یا هر چیز دیگه)
        "django.core.cache": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
        # لاگ جنگو اکسس (برای دیدن عملیات axes)
        "axes": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
        # لاگ عمومی برای دیباگ شخصی
        "debug_logger": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}


KAVENEGAR_API_KEY = os.getenv("KAVENEGAR_API")
KAVENEGAR_SENDER = os.getenv("KAVENEGAR_SENDER")
