# Generated by Django 6.0.3 on 2026-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="allinonepc",
            name="colors",
            field=models.ManyToManyField(to="shop.colors", verbose_name="Colors"),
        ),
    ]
