# Generated by Django 6.0.3 on 2026-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_allinonepc_slug_alter_bluetoothdongle_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allinonepc",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="bluetoothdongle",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="computercase",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="cpumodel",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="externalharddrive",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="externalssd",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="flashdrive",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="graphicscard",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="internalhdd",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="laptoprammodel",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="prebuiltpc",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="ssd",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="usbhub",
            name="price",
            field=models.PositiveBigIntegerField(default=0, verbose_name="price"),
        ),
    ]
