# Generated by Django 6.0.3 on 2026-03-16 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_allinonepc_price_alter_bluetoothdongle_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colors",
            options={"verbose_name": "Color ", "verbose_name_plural": "Colors"},
        ),
        migrations.AlterModelOptions(
            name="graphicscardfeatures",
            options={
                "verbose_name": "Graphics Card Feature",
                "verbose_name_plural": "Graphics Card Features",
            },
        ),
        migrations.AlterModelOptions(
            name="operationsystemssupported",
            options={
                "verbose_name": "Operation System ",
                "verbose_name_plural": "Operation Systems ",
            },
        ),
        migrations.AlterModelOptions(
            name="pcigenerationtypes",
            options={
                "verbose_name": "PCI Generation Type",
                "verbose_name_plural": "PCI Generation Types",
            },
        ),
        migrations.AlterModelOptions(
            name="raidtypessupported",
            options={
                "verbose_name": "RAID Type Supported",
                "verbose_name_plural": "RAID Types Supported",
            },
        ),
        migrations.AlterModelOptions(
            name="ramtypessupported",
            options={
                "verbose_name": "RAM Type Supported",
                "verbose_name_plural": "RAM Types Supported",
            },
        ),
    ]
