# Generated by Django 6.0.3 on 2026-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_colors_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpumodel",
            name="cpu_generation",
            field=models.CharField(max_length=300, verbose_name="cpu generation"),
        ),
    ]
