# Generated by Django 6.0.3 on 2026-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_cpumodel_cpu_generation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpumodel",
            name="cpu_generation",
            field=models.PositiveIntegerField(default=0, verbose_name="cpu generation"),
        ),
    ]
