# Generated by Django 6.0.3 on 2026-03-23 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_newsletter_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "verbose_name": "News Letter",
                "verbose_name_plural": "News Letters",
            },
        ),
    ]
