# Generated by Django 6.0.3 on 2026-03-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_comment_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allinonepc",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="bluetoothdongle",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="computercase",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="cpumodel",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="externalharddrive",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="externalssd",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="flashdrive",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="graphicscard",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="internalhdd",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="laptoprammodel",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="prebuiltpc",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="ssd",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="usbhub",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
    ]
