# Generated by Django 6.0.3 on 2026-03-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_allinonepc_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allinonepc",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="bluetoothdongle",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="computercase",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="cpumodel",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="externalharddrive",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="externalssd",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="flashdrive",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="graphicscard",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="internalhdd",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="laptoprammodel",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="prebuiltpc",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="ssd",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
        migrations.AlterField(
            model_name="usbhub",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main_images/",
                verbose_name="main image",
            ),
        ),
    ]
