# Generated by Django 6.0.3 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_allinonepc_main_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allinonepc",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="bluetoothdongle",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="computercase",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="cpumodel",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="externalharddrive",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="externalssd",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="flashdrive",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="graphicscard",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="internalhdd",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="keyboard",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="laptop",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="laptoprammodel",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="motherboard",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="prebuiltpc",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="ssd",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
        migrations.AddField(
            model_name="usbhub",
            name="summary",
            field=models.CharField(
                default="None", max_length=255, verbose_name="summary"
            ),
        ),
    ]
