# Generated by Django 6.0.3 on 2026-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_alter_allinonepc_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allinonepc",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="bluetoothdongle",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="computercase",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="cpumodel",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="externalharddrive",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="externalssd",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="flashdrive",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="graphicscard",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="internalhdd",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="keyboard",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="laptoprammodel",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="prebuiltpc",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="ssd",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="usbhub",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=3000, unique=True, verbose_name="slug"
            ),
        ),
    ]
