# Generated by Django 6.0.3 on 2026-04-19 08:14

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_returnrequest_returnitem_returnimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                default=orders.models.generate_discount_code,
                max_length=50,
                unique=True,
                verbose_name="Code",
            ),
        ),
    ]
