# Generated by Django 6.0.3 on 2026-04-19 10:41

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_discount_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                default=orders.models.generate_tracking_code,
                max_length=255,
                verbose_name="Tracking code",
            ),
        ),
    ]
