# Generated by Django 6.0.3 on 2026-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("preparing", "preparing"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                    ("returned", "returned"),
                ],
                default="preparing",
                max_length=20,
                verbose_name="Delivery status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gateway_ref_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="gateway refid"
            ),
        ),
    ]
