# Generated by Django 6.0.3 on 2026-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_delivery_status_order_gateway_ref_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
